import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { DarkModeToggle } from "@/components/darkModeToggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider attribute="class" defaultTheme="system">
        <body className={inter.className}>
          <nav className="flex  p-4">
            <ul className="mr-auto">
              <li>or-yam</li>
            </ul>
            <DarkModeToggle />
          </nav>
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
